# Site settings
title: Reece Nicholls | Full-Stack .NET & Software Engineer
description: Hi, I'm Reece Nicholls. Full-Stack .NET & Software Engineer. I build enterprise web applications, backend services, and cloud infrastructure.
url: "https://www.reecenicholls.co.uk"
email: "contact@reecenicholls.co.uk"
lang: "en-GB"
locale: "en_GB"

# Build settings
plugins:
  - jekyll-sitemap

exclude:
  - _archive
  - Gemfile
  - Gemfile.lock
  - README.md
  - .DS_Store
  - .github
