# Site settings
title: Reece Nicholls | Full-Stack .NET & Software Engineer
description: Full-Stack .NET & Software Engineer specialising in C#, .NET, Azure, DevOps, CI/CD automation, and web architecture.
url: "https://www.reecenicholls.co.uk"
email: "contact@reecenicholls.co.uk"
lang: "en-GB"
locale: "en_GB"

# Build settings
exclude:
  - _archive
  - Gemfile
  - Gemfile.lock
  - README.md
  - .DS_Store
