title: Reece Nicholls
author:
  name: Reece Nicholls
  # email: your-email@domain.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Reece Nicholls and I am an undergraduate student studying
  Business Computing BSc(Hons) at the University of the West of England (UWE), UK.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github: ReeceNich
    linkedin: reece-nicholls
    youtube_channel: UC7d2ZXWMuBfxsAhcXrlvS6Q
    youtube_channel_name: Reece Nicholls


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md
# - projects.md
# - youtube.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
